volumes:
  pb_data:
  pb_public:

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pb_data:/pb_data
      - pb_public:/pb_public
  
