FROM denoland/deno:alpine-1.38.0

EXPOSE 8000

WORKDIR /app

ENV COMPOSE_PROFILE=prod

USER deno
COPY deno.json .
COPY deno.lock .
COPY ./startup.sh ./startup.sh

ADD migrations migrations
ADD src src
RUN deno cache -c deno.json src/main.ts

ADD migrate.ts migrate.ts
ADD .env.defaults .env.defaults

# RUN deno cache --allow-write ./src/main.ts
ENTRYPOINT [ "/bin/sh" ]
CMD ["./startup.sh"]